redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
#  build: ./
#  volumes:
#    - ./:/var/www/app

  image: mrizwanyaqub/at-api
  links:
    - redis
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://cache
  ##command:
    ##sh -c 'node src/index.js'